version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  # volumes:
  #   - ./folder:/container_folder
  adminer:
    image: adminer
    ports:
      - 8080:8080